apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-var
spec:
  replicas: 1
  selector:
    matchLabels:
      app: print-var
  template:
    metadata:
      labels:
        app: print-var
    spec:
      containers:
      - name: print-var
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo My variable is: $MY_VARIABLE; sleep 3600"]
        env:
        - name: MY_VARIABLE
          value: {{ .Values.myVariable | quote }}
