apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-var
  namespace: kv-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: print-var
  template:
    metadata:
      labels:
        app: print-var
    spec:
      containers:
      - name: print-var
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo My variable is: $MY_VARIABLE; echo MY_VARIABLE_FROM_HELM is: $MY_VARIABLE_FROM_HELM; sleep 3600"]
        env: 
        - name: MY_VARIABLE_FROM_HELM 
          value: {{ .Values.myVariable | quote }}
        - name: MY_VARIABLE
          valueFrom:
            secretKeyRef:
              name: imported-kv-secrets
              key: mytoken
